input {
  beats {
    port => 5044
    host => "0.0.0.0"
  }
}

filter {
  grok {
    match => {
      "message" => '%{IPORHOST:client_ip} - %{DATA:remote_user} \[%{HTTPDATE:time_local}\] \"%{WORD:method} %{URIPATHPARAM:request} HTTP/%{NUMBER:http_version}\" %{NUMBER:status} %{NUMBER:body_bytes_sent} \"%{DATA:http_referer}\" \"%{DATA:http_user_agent}\" \"%{DATA:http_x_forwarded_for}\" %{NUMBER:request_time} %{DATA:upstream_response_time}'
    }
  }

  date {
    match => ["time_local", "dd/MMM/yyyy:HH:mm:ss Z"]
    target => "@timestamp"
    remove_field => ["time_local"]
  }

  mutate {
    convert => {
      "status"          => "integer"
      "body_bytes_sent" => "integer"
      "request_time"    => "float"
      "http_version"    => "float"
    }
  }

  # Handle upstream_response_time being "-" or a number
  if [upstream_response_time] != "-" {
    mutate {
      convert => { "upstream_response_time" => "float" }
    }
  }

  if [request_time] and [request_time] > 1 {
    mutate {
      add_tag => ["slow_request"]
    }
  }
}

output {
  elasticsearch {
    hosts    => ["https://localhost:9200"]
    index    => "nginx-logs-%{+yyyy.MM.dd}"
    user     => "elastic"
    password => "S=0MyJP5YPd1AynF6EaE"
    ssl_verification_mode => "none"
  }
}