input {
  beats {
    port => 5044
  }
}

filter {
  # -------------------------
  # NGINX ACCESS LOG PARSING
  # -------------------------
  if [log][file][path] == "/var/log/nginx/access.log" or "nginx.access" in [fileset][name] {
    grok {
      match => {
        "message" => [
          '%{IPORHOST:client_ip} - %{DATA:remote_user} \[%{HTTPDATE:time_local}\] \"%{WORD:method} %{URIPATHPARAM:request} HTTP/%{NUMBER:http_version}\" %{NUMBER:status} %{NUMBER:body_bytes_sent} \"%{DATA:http_referer}\" \"%{DATA:http_user_agent}\" \"%{DATA:http_x_forwarded_for}\" %{NUMBER:request_time} %{DATA:upstream_response_time}'
        ]
      }
      remove_field => ["message"]
    }

    date {
      match => ["time_local", "dd/MMM/yyyy:HH:mm:ss Z"]
      target => "@timestamp"
      remove_field => ["time_local"]
    }

    mutate {
      convert => {
        "status"          => "integer"
        "body_bytes_sent" => "integer"
        "request_time"    => "float"
        "http_version"    => "float"
      }
    }
  }

  # -------------------------
  # NGINX ERROR LOG (optional)
  # -------------------------
  else if [log][file][path] == "/var/log/nginx/error.log" {
    mutate { add_field => { "log_type" => "nginx_error" } }
    # keep raw for now (nginx error parsing can be added later)
  }

  # -------------------------
  # K8S / EKS CONTAINER LOGS
  # -------------------------
  else if [kubernetes] or [kubernetes][pod] {
    mutate { add_field => { "log_type" => "k8s_container" } }
    # keep raw for now (you can add json parsing later if app logs are json)
  }
}

output {
  if [log_type] == "k8s_container" {
    elasticsearch {
      hosts => ["https://localhost:9200"]
      index => "k8s-containers-%{+YYYY.MM.dd}"
      user => "elastic"
      password => "S=0MyJP5YPd1AynF6EaE"
      ssl_enabled => true
      ssl_verification_mode => "none"
    }
  } else if [log_type] == "nginx_access" {
    elasticsearch {
      hosts => ["https://localhost:9200"]
      index => "nginx-access-%{+YYYY.MM.dd}"
      user => "elastic"
      password => "S=0MyJP5YPd1AynF6EaE"
      ssl_enabled => true
      ssl_verification_mode => "none"
    }
  } else if [log_type] == "nginx_error" {
    elasticsearch {
      hosts => ["https://localhost:9200"]
      index => "nginx-error-%{+YYYY.MM.dd}"
      user => "elastic"
      password => "S=0MyJP5YPd1AynF6EaE"
      ssl_enabled => true
      ssl_verification_mode => "none"
    }
  } else {
    elasticsearch {
      hosts => ["https://localhost:9200"]
      index => "beats-raw-%{+YYYY.MM.dd}"
      user => "elastic"
      password => "S=0MyJP5YPd1AynF6EaE"
      ssl_enabled => true
      ssl_verification_mode => "none"
    }
  }

  stdout { codec => rubydebug }
}